# Generated by Django 4.2.11 on 2024-04-26 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoqueADS', '0003_produtos_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
